name: CI

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_build:
    name: Cargo Build
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --verbose
  cargo_test:
    name: Cargo Test
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15]
    runs-on: ${{ matrix.os }}
    needs:
      - cargo_build
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --verbose
  types:
    name: Test Types
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: ESlint
        run: pnpm lint
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: ESlint
        run: pnpm lint
